[book]
authors = ["João Paulo Taylor Ienczak Zanette"]
multilingual = false
src = "src"
title = "Python"

[build]
build-dir = "../../book/langs/python"

[output.html]
additional-css = ["../../css/special-tags.css"]
additional-js = ["../../js/special-tags.js"]
